CREATE SEQUENCE public.sessions_session_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.sessions (
	session_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	session_uuid CHAR(36) NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT sessions_pkey PRIMARY KEY (session_id ASC)
);
CREATE SEQUENCE public.users_user_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.users (
	user_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	display_name VARCHAR(50) NULL,
	display_name_index INT8 NULL DEFAULT 0:::INT8,
	email VARCHAR(255) NULL,
	password_hash BYTES NULL,
	admin BOOL NULL DEFAULT false,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	profile_picture_uuid VARCHAR(36) NULL,
	slug VARCHAR(70) NULL,
	bio VARCHAR(500) NULL,
	subscribed_to_users INT8 NULL DEFAULT 0:::INT8,
	CONSTRAINT users_pkey PRIMARY KEY (user_id ASC)
);
CREATE TABLE public.user_sessions (
	user_id INT8 NOT NULL,
	session_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT user_sessions_pkey PRIMARY KEY (user_id ASC, session_id ASC)
);
CREATE SEQUENCE public.reset_tokens_token_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.reset_tokens (
	token_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	token_uuid CHAR(36) NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT reset_tokens_pkey PRIMARY KEY (token_id ASC)
);
CREATE SEQUENCE public.subscriptions_subscription_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.subscriptions (
	subscription_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	subscription_json VARCHAR(1024) NULL,
	fcm_token VARCHAR(1024) NULL,
	active BOOL NULL DEFAULT true,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id ASC),
	INDEX idx_subscriptions_user_id (user_id ASC) STORING (subscription_json, fcm_token, active)
);
CREATE SEQUENCE public.blocked_users_blocked_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.blocked_users (
	blocked_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id_blocked INT8 NOT NULL,
	user_id_blocking INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT blocked_users_pkey PRIMARY KEY (blocked_id ASC),
	INDEX idx_blocked_users_user_id_blocking (user_id_blocking ASC) STORING (user_id_blocked)
);
CREATE SEQUENCE public.subscribers_subscriber_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.subscribers (
	subscriber_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	subscribed_to_user_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT subscribers_pkey PRIMARY KEY (subscriber_id ASC),
	INDEX idx_subscribers_user_id_subscribed_to_user_id (user_id ASC, subscribed_to_user_id ASC)
);
CREATE SEQUENCE public.replies_reply_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.replies (
	reply_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	parent_post_id INT8 NULL,
	parent_reply_id INT8 NULL,
	body VARCHAR(8000) NULL,
	note VARCHAR(500) NULL,
	image_uuids VARCHAR(147) NULL,
	favorite_count INT8 NULL DEFAULT 0:::INT8,
	counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	user_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	image_dimensions VARCHAR(31) NULL,
	CONSTRAINT replies_pkey PRIMARY KEY (reply_id ASC),
	INDEX idx_replies_create_date (create_date ASC) STORING (parent_post_id, parent_reply_id, body, note, user_id, favorite_count, counts_max_create_date),
	INDEX idx_replies_parent_reply_id (parent_reply_id ASC),
	INDEX idx_replies_parent_post_id (parent_post_id ASC) STORING (user_id),
	INDEX idx_replies_create_date_counts_max_create_date (create_date ASC, counts_max_create_date ASC) STORING (favorite_count),
	INDEX idx_replies_parent_post_id_parent_reply_id_user_id (parent_post_id ASC, parent_reply_id ASC, user_id ASC) STORING (body, note, create_date, favorite_count, counts_max_create_date)
);
CREATE TABLE public.reply_ancestors (
	reply_id INT8 NOT NULL,
	ancestor_reply_id INT8 NOT NULL,
	rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
	CONSTRAINT reply_ancestors_pkey PRIMARY KEY (rowid ASC),
	INDEX idx_reply_ancestor (reply_id ASC, ancestor_reply_id ASC),
	UNIQUE INDEX unique_reply_ancestor (reply_id ASC, ancestor_reply_id ASC)
);
CREATE SEQUENCE public.favorite_posts_favorite_post_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.favorite_posts (
	favorite_post_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	post_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT favorite_posts_pkey PRIMARY KEY (favorite_post_id ASC),
	INDEX idx_favorites_posts_user_id (user_id ASC) STORING (post_id),
	INDEX idx_favorites_posts_post_id (post_id ASC) STORING (user_id)
);
CREATE SEQUENCE public.favorite_replies_favorite_reply_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.favorite_replies (
	favorite_reply_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	reply_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT favorite_replies_pkey PRIMARY KEY (favorite_reply_id ASC),
	INDEX idx_favorites_replies_user_id (user_id ASC) STORING (reply_id),
	INDEX idx_favorites_replies_reply_id (reply_id ASC) STORING (user_id)
);
CREATE SEQUENCE public.flagged_posts_flagged_post_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.flagged_posts (
	flagged_post_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	post_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT flagged_posts_pkey PRIMARY KEY (flagged_post_id ASC),
	INDEX idx_flagged_posts_post_id (post_id ASC)
);
CREATE SEQUENCE public.flagged_replies_flagged_reply_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.flagged_replies (
	flagged_reply_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	reply_id INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT flagged_replies_pkey PRIMARY KEY (flagged_reply_id ASC),
	INDEX idx_flagged_replies_reply_id (reply_id ASC)
);
CREATE SEQUENCE public.post_poll_votes_poll_vote_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.post_poll_votes (
	poll_vote_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	post_id INT8 NOT NULL,
	user_id INT8 NOT NULL,
	poll_choice INT8 NOT NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT post_poll_votes_pkey PRIMARY KEY (poll_vote_id ASC),
	INDEX idx_post_poll_votes_post_id_user_id (post_id ASC, user_id ASC),
	CONSTRAINT check_poll_choice CHECK (poll_choice BETWEEN 1:::INT8 AND 4:::INT8)
);
CREATE SEQUENCE public.reply_notifications_notification_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.reply_notifications (
	notification_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	reply_id INT8 NULL,
	read BOOL NULL DEFAULT false,
	seen BOOL NULL DEFAULT false,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT reply_notifications_pkey PRIMARY KEY (notification_id ASC),
	INDEX idx_reply_notifications_user_id_create_date_read_seen (user_id ASC, create_date ASC, read ASC, seen ASC)
);
CREATE SEQUENCE public.posts_post_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.posts (
	post_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(140) NULL,
	body VARCHAR(8000) NULL,
	note VARCHAR(500) NULL,
	slug VARCHAR(140) NULL,
	image_uuids VARCHAR(147) NULL,
	reply_count INT8 NULL DEFAULT 0:::INT8,
	favorite_count INT8 NULL DEFAULT 0:::INT8,
	poll_counts VARCHAR(50) NULL,
	poll_counts_estimated VARCHAR(50) NULL,
	poll_1 VARCHAR(50) NULL,
	poll_2 VARCHAR(50) NULL,
	poll_3 VARCHAR(50) NULL,
	poll_4 VARCHAR(50) NULL,
	poll_expire_date TIMESTAMP(3) NULL,
	counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	user_id INT8 NOT NULL,
	admin BOOL NULL DEFAULT false,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	image_dimensions VARCHAR(31) NULL,
	CONSTRAINT posts_pkey PRIMARY KEY (post_id ASC),
	INDEX idx_posts_create_date (create_date ASC),
	INDEX idx_posts_create_date_counts_max_create_date (create_date ASC, counts_max_create_date ASC) STORING (reply_count, favorite_count),
	INDEX idx_posts_counts_max_create_date (counts_max_create_date ASC) STORING (reply_count, create_date, favorite_count)
);
CREATE SEQUENCE public.topics_topic_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.topics (
	topic_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	topic_name VARCHAR(10) NOT NULL,
	subtitle VARCHAR(50) NOT NULL,
	CONSTRAINT topics_pkey PRIMARY KEY (topic_id ASC),
	UNIQUE INDEX topics_topic_name_key (topic_name ASC),
	INDEX idx_topics_topic_id_topic_name (topic_id ASC, topic_name ASC),
	UNIQUE INDEX unique_topic_name (topic_name ASC)
);
CREATE TABLE public.post_topics (
	post_id INT8 NOT NULL,
	topic_id INT8 NOT NULL,
	rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
	CONSTRAINT post_topics_pkey PRIMARY KEY (rowid ASC),
	INDEX idx_post_topics_post_id_topic_id (post_id ASC, topic_id ASC),
	UNIQUE INDEX unique_post_topic (post_id ASC, topic_id ASC)
);
CREATE SEQUENCE public.message_notifications_notification_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.message_notifications (
	notification_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT8 NOT NULL,
	message_id INT8 NOT NULL,
	read BOOL NULL DEFAULT false,
	seen BOOL NULL DEFAULT false,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT message_notifications_pkey PRIMARY KEY (notification_id ASC),
	INDEX idx_message_notifications_user_id_create_date_read_seen (user_id ASC, create_date ASC, read ASC, seen ASC),
	INDEX idx_message_notifications_message_id (message_id ASC)
);
CREATE SEQUENCE public.conversations_conversation_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.conversations (
	conversation_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	last_message_id INT8 NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	CONSTRAINT conversations_pkey PRIMARY KEY (conversation_id ASC)
);
CREATE TABLE public.conversation_users (
	conversation_id INT8 NOT NULL,
	user_id INT8 NOT NULL,
	CONSTRAINT conversation_users_pkey PRIMARY KEY (conversation_id ASC, user_id ASC),
	INDEX idx_conversation_users_user_id (user_id ASC)
);
CREATE SEQUENCE public.messages_message_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE TABLE public.messages (
	message_id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	conversation_id INT8 NOT NULL,
	user_id INT8 NOT NULL,
	body VARCHAR(8000) NULL,
	note VARCHAR(500) NULL,
	image_uuids VARCHAR(147) NULL,
	create_date TIMESTAMP(3) NOT NULL DEFAULT now():::TIMESTAMP,
	image_dimensions VARCHAR(31) NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (message_id ASC),
	INDEX idx_messages_conversation_id_create_date (conversation_id ASC, create_date ASC) STORING (user_id, body, image_uuids),
	INDEX idx_messages_user_id (user_id ASC)
);
