-- truce-web schema — translated from CockroachDB v25.4 to PostgreSQL 16
-- Source of truth: `SHOW CREATE ALL TABLES` on the live Cockroach cluster
-- (captured in migration/cockroach_schema.sql).
--
-- Translation notes (Cockroach -> Postgres):
--   * Explicit `CREATE SEQUENCE ..._seq` dropped: Postgres IDENTITY columns
--     own their sequence implicitly.
--   * INT8 -> BIGINT, BYTES -> BYTEA, BOOL -> BOOLEAN.
--   * `now():::TIMESTAMP` -> `now()`; `N:::INT8` default casts -> `N`.
--   * Inline `INDEX ...`/`UNIQUE INDEX ...` extracted to separate CREATE [UNIQUE] INDEX.
--   * Cockroach `STORING (cols)` -> Postgres `INCLUDE (cols)`, BUT only where every
--     payload column is small + fixed-width (bigint/bool/timestamp). Postgres B-tree
--     index tuples are capped at ~2704 bytes, so any STORING list containing a large
--     text column (body VARCHAR(8000), note, *_json, fcm_token, image_uuids) would
--     overflow on long rows. For those indexes the key columns are preserved and the
--     payload is dropped (covering payload is a pure perf optimization with no
--     measurable benefit at this data scale).
--   * `reply_ancestors` / `post_topics` had a hidden `rowid ... unique_rowid()` PK
--     (Cockroach-only). Replaced with their natural composite UNIQUE key as the PK.
--     Verified the app never references `rowid` and never SELECT *'s these tables.
--   * No FOREIGN KEY constraints exist in the source (integrity is app-level), so
--     table/data load order is irrelevant.

DROP TABLE IF EXISTS
  sessions, users, user_sessions, reset_tokens, subscriptions, blocked_users,
  subscribers, replies, reply_ancestors, favorite_posts, favorite_replies,
  flagged_posts, flagged_replies, post_poll_votes, reply_notifications, posts,
  topics, post_topics, message_notifications, conversations, conversation_users,
  messages
CASCADE;

CREATE TABLE sessions (
  session_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_uuid CHAR(36) NOT NULL,
  create_date  TIMESTAMP(3) NOT NULL DEFAULT now()
);

CREATE TABLE users (
  user_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name         VARCHAR(50),
  display_name_index   BIGINT DEFAULT 0,
  email                VARCHAR(255),
  password_hash        BYTEA,
  admin                BOOLEAN DEFAULT false,
  create_date          TIMESTAMP(3) NOT NULL DEFAULT now(),
  profile_picture_uuid VARCHAR(36),
  slug                 VARCHAR(70),
  bio                  VARCHAR(500),
  subscribed_to_users  BIGINT DEFAULT 0
);

CREATE TABLE user_sessions (
  user_id     BIGINT NOT NULL,
  session_id  BIGINT NOT NULL,
  create_date TIMESTAMP(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, session_id)
);

CREATE TABLE reset_tokens (
  token_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  token_uuid  CHAR(36) NOT NULL,
  create_date TIMESTAMP(3) NOT NULL DEFAULT now()
);

CREATE TABLE subscriptions (
  subscription_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL,
  subscription_json VARCHAR(1024),
  fcm_token         VARCHAR(1024),
  active            BOOLEAN DEFAULT true,
  create_date       TIMESTAMP(3) NOT NULL DEFAULT now()
);
-- STORING (subscription_json, fcm_token, active) dropped: variable-length text payload.
CREATE INDEX idx_subscriptions_user_id ON subscriptions (user_id);

CREATE TABLE blocked_users (
  blocked_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_blocked  BIGINT NOT NULL,
  user_id_blocking BIGINT NOT NULL,
  create_date      TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_blocked_users_user_id_blocking ON blocked_users (user_id_blocking) INCLUDE (user_id_blocked);

CREATE TABLE subscribers (
  subscriber_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              BIGINT NOT NULL,
  subscribed_to_user_id BIGINT NOT NULL,
  create_date          TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_subscribers_user_id_subscribed_to_user_id ON subscribers (user_id, subscribed_to_user_id);

CREATE TABLE replies (
  reply_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_post_id         BIGINT,
  parent_reply_id        BIGINT,
  body                   VARCHAR(8000),
  note                   VARCHAR(500),
  image_uuids            VARCHAR(147),
  favorite_count         BIGINT DEFAULT 0,
  counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT now(),
  user_id                BIGINT NOT NULL,
  create_date            TIMESTAMP(3) NOT NULL DEFAULT now(),
  image_dimensions       VARCHAR(31)
);
-- STORING with body/note dropped (would overflow B-tree tuple limit); keys preserved.
CREATE INDEX idx_replies_create_date ON replies (create_date);
CREATE INDEX idx_replies_parent_reply_id ON replies (parent_reply_id);
CREATE INDEX idx_replies_parent_post_id ON replies (parent_post_id) INCLUDE (user_id);
CREATE INDEX idx_replies_create_date_counts_max_create_date ON replies (create_date, counts_max_create_date) INCLUDE (favorite_count);
CREATE INDEX idx_replies_parent_post_id_parent_reply_id_user_id ON replies (parent_post_id, parent_reply_id, user_id);

CREATE TABLE reply_ancestors (
  reply_id          BIGINT NOT NULL,
  ancestor_reply_id BIGINT NOT NULL,
  PRIMARY KEY (reply_id, ancestor_reply_id)
);

CREATE TABLE favorite_posts (
  favorite_post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  post_id          BIGINT NOT NULL,
  create_date      TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_favorites_posts_user_id ON favorite_posts (user_id) INCLUDE (post_id);
CREATE INDEX idx_favorites_posts_post_id ON favorite_posts (post_id) INCLUDE (user_id);

CREATE TABLE favorite_replies (
  favorite_reply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL,
  reply_id          BIGINT NOT NULL,
  create_date       TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_favorites_replies_user_id ON favorite_replies (user_id) INCLUDE (reply_id);
CREATE INDEX idx_favorites_replies_reply_id ON favorite_replies (reply_id) INCLUDE (user_id);

CREATE TABLE flagged_posts (
  flagged_post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  post_id         BIGINT NOT NULL,
  create_date     TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_flagged_posts_post_id ON flagged_posts (post_id);

CREATE TABLE flagged_replies (
  flagged_reply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  reply_id         BIGINT NOT NULL,
  create_date      TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_flagged_replies_reply_id ON flagged_replies (reply_id);

CREATE TABLE post_poll_votes (
  poll_vote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id      BIGINT NOT NULL,
  user_id      BIGINT NOT NULL,
  poll_choice  BIGINT NOT NULL,
  create_date  TIMESTAMP(3) NOT NULL DEFAULT now(),
  CONSTRAINT check_poll_choice CHECK (poll_choice BETWEEN 1 AND 4)
);
CREATE INDEX idx_post_poll_votes_post_id_user_id ON post_poll_votes (post_id, user_id);

CREATE TABLE reply_notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  reply_id        BIGINT,
  read            BOOLEAN DEFAULT false,
  seen            BOOLEAN DEFAULT false,
  create_date     TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_reply_notifications_user_id_create_date_read_seen ON reply_notifications (user_id, create_date, read, seen);

CREATE TABLE posts (
  post_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                  VARCHAR(140),
  body                   VARCHAR(8000),
  note                   VARCHAR(500),
  slug                   VARCHAR(140),
  image_uuids            VARCHAR(147),
  reply_count            BIGINT DEFAULT 0,
  favorite_count         BIGINT DEFAULT 0,
  poll_counts            VARCHAR(50),
  poll_counts_estimated  VARCHAR(50),
  poll_1                 VARCHAR(50),
  poll_2                 VARCHAR(50),
  poll_3                 VARCHAR(50),
  poll_4                 VARCHAR(50),
  poll_expire_date       TIMESTAMP(3),
  counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT now(),
  user_id                BIGINT NOT NULL,
  admin                  BOOLEAN DEFAULT false,
  create_date            TIMESTAMP(3) NOT NULL DEFAULT now(),
  image_dimensions       VARCHAR(31)
);
CREATE INDEX idx_posts_create_date ON posts (create_date);
CREATE INDEX idx_posts_create_date_counts_max_create_date ON posts (create_date, counts_max_create_date) INCLUDE (reply_count, favorite_count);
CREATE INDEX idx_posts_counts_max_create_date ON posts (counts_max_create_date) INCLUDE (reply_count, create_date, favorite_count);

CREATE TABLE topics (
  topic_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_name VARCHAR(10) NOT NULL,
  subtitle   VARCHAR(50) NOT NULL,
  CONSTRAINT unique_topic_name UNIQUE (topic_name)
);
CREATE INDEX idx_topics_topic_id_topic_name ON topics (topic_id, topic_name);

CREATE TABLE post_topics (
  post_id  BIGINT NOT NULL,
  topic_id BIGINT NOT NULL,
  PRIMARY KEY (post_id, topic_id)
);

CREATE TABLE message_notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  message_id      BIGINT NOT NULL,
  read            BOOLEAN DEFAULT false,
  seen            BOOLEAN DEFAULT false,
  create_date     TIMESTAMP(3) NOT NULL DEFAULT now()
);
CREATE INDEX idx_message_notifications_user_id_create_date_read_seen ON message_notifications (user_id, create_date, read, seen);
CREATE INDEX idx_message_notifications_message_id ON message_notifications (message_id);

CREATE TABLE conversations (
  conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_message_id BIGINT,
  create_date     TIMESTAMP(3) NOT NULL DEFAULT now()
);

CREATE TABLE conversation_users (
  conversation_id BIGINT NOT NULL,
  user_id         BIGINT NOT NULL,
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX idx_conversation_users_user_id ON conversation_users (user_id);

CREATE TABLE messages (
  message_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  user_id         BIGINT NOT NULL,
  body            VARCHAR(8000),
  note            VARCHAR(500),
  image_uuids     VARCHAR(147),
  create_date     TIMESTAMP(3) NOT NULL DEFAULT now(),
  image_dimensions VARCHAR(31)
);
-- STORING (user_id, body, image_uuids) dropped (body would overflow tuple limit); keys preserved.
CREATE INDEX idx_messages_conversation_id_create_date ON messages (conversation_id, create_date);
CREATE INDEX idx_messages_user_id ON messages (user_id);
