const pool = require("./pool")

module.exports = {
	async init() {
		const client = await pool.pool.connect()
		try {
			await client.query(`
-- ================================
-- UNCHANGED EXISTING TABLES
-- ================================

CREATE TABLE IF NOT EXISTS sessions (
session_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
session_uuid CHAR(36) NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
display_name VARCHAR(50),
display_name_index INT DEFAULT 0,
email VARCHAR(255),
password_hash BYTEA,
profile_picture_uuid VARCHAR(36),
admin BOOL DEFAULT false,
slug VARCHAR(70),
bio VARCHAR(500),
subscribed_to_users INT DEFAULT 0,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
user_id INT NOT NULL,
session_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW(),
PRIMARY KEY (user_id, session_id)
);

CREATE TABLE IF NOT EXISTS reset_tokens (
token_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
token_uuid CHAR(36) NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscriptions (
subscription_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
subscription_json VARCHAR(1024),
fcm_token VARCHAR(1024),
active BOOL DEFAULT true,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id) STORING (subscription_json, fcm_token, active);

CREATE TABLE IF NOT EXISTS blocked_users (
blocked_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id_blocked INT NOT NULL,
user_id_blocking INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_blocked_users_user_id_blocking ON blocked_users(user_id_blocking) STORING (user_id_blocked);

CREATE TABLE IF NOT EXISTS subscribers (
subscriber_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
subscribed_to_user_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscribers_user_id_subscribed_to_user_id ON subscribers(user_id, subscribed_to_user_id);

CREATE TABLE IF NOT EXISTS tags (
tag_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
tag_name VARCHAR(10) NOT NULL UNIQUE,
subtitle VARCHAR(50) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tags_tag_id_tag_name ON tags(tag_id, tag_name);

-- ================================
-- NEW TABLES (PHASE 2)
-- ================================

-- topics (formerly tags)
CREATE TABLE IF NOT EXISTS topics (
topic_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
topic_name VARCHAR(10) NOT NULL UNIQUE,
subtitle VARCHAR(50) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_topics_topic_id_topic_name ON topics(topic_id, topic_name);

-- ================================
-- NEW TABLES (PHASE 1)
-- ================================

-- posts (formerly topics)
CREATE TABLE IF NOT EXISTS posts (
post_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR(140),
body VARCHAR(8000),
note VARCHAR(500),
slug VARCHAR(140),
image_uuids VARCHAR(147),
reply_count INT DEFAULT 0,
favorite_count INT DEFAULT 0,
poll_counts VARCHAR(50),
poll_counts_estimated VARCHAR(50),
poll_1 VARCHAR(50),
poll_2 VARCHAR(50),
poll_3 VARCHAR(50),
poll_4 VARCHAR(50),
poll_expire_date TIMESTAMP(3),
counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT NOW(),
user_id INT NOT NULL,
admin BOOL DEFAULT false,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_posts_create_date ON posts(create_date);
CREATE INDEX IF NOT EXISTS idx_posts_create_date_counts_max_create_date 
ON posts(create_date, counts_max_create_date)
STORING (reply_count, favorite_count);
CREATE INDEX IF NOT EXISTS idx_posts_counts_max_create_date ON posts(counts_max_create_date) STORING (reply_count, create_date, favorite_count);

-- replies (formerly comments)
CREATE TABLE IF NOT EXISTS replies (
reply_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
parent_post_id INT,
parent_reply_id INT,
body VARCHAR(8000),
note VARCHAR(500),
image_uuids VARCHAR(147),
favorite_count INT DEFAULT 0,
counts_max_create_date TIMESTAMP(3) NOT NULL DEFAULT NOW(),
user_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_replies_create_date ON replies(create_date) STORING (parent_post_id, parent_reply_id, body, note, user_id, favorite_count, counts_max_create_date);
CREATE INDEX IF NOT EXISTS idx_replies_parent_reply_id ON replies(parent_reply_id);
CREATE INDEX IF NOT EXISTS idx_replies_parent_post_id ON replies(parent_post_id) STORING (user_id);
CREATE INDEX IF NOT EXISTS idx_replies_create_date_counts_max_create_date 
ON replies(create_date, counts_max_create_date)
STORING (favorite_count);
CREATE INDEX IF NOT EXISTS idx_replies_parent_post_id_parent_reply_id_user_id ON replies (parent_post_id, parent_reply_id, user_id) STORING (body, note, create_date, favorite_count, counts_max_create_date);

-- reply_ancestors (formerly comment_ancestors)
CREATE TABLE IF NOT EXISTS reply_ancestors (
reply_id INT NOT NULL,
ancestor_reply_id INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reply_ancestor ON reply_ancestors (reply_id, ancestor_reply_id);
ALTER TABLE reply_ancestors
ADD CONSTRAINT IF NOT EXISTS unique_reply_ancestor UNIQUE (reply_id, ancestor_reply_id);

-- post_tags (formerly topic_tags)
CREATE TABLE IF NOT EXISTS post_tags (
post_id INT NOT NULL,
tag_id INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_post_tags_post_id_tag_id ON post_tags(post_id, tag_id);
ALTER TABLE post_tags
ADD CONSTRAINT IF NOT EXISTS unique_post_tag UNIQUE (post_id, tag_id);

-- post_topics (formerly post_tags)
CREATE TABLE IF NOT EXISTS post_topics (
post_id INT NOT NULL,
topic_id INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_post_topics_post_id_topic_id ON post_topics(post_id, topic_id);
ALTER TABLE post_topics
ADD CONSTRAINT IF NOT EXISTS unique_post_topic UNIQUE (post_id, topic_id);

-- favorite_posts (formerly favorite_topics)
CREATE TABLE IF NOT EXISTS favorite_posts (
favorite_post_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
post_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_favorites_posts_user_id ON favorite_posts(user_id) STORING (post_id);
CREATE INDEX IF NOT EXISTS idx_favorites_posts_post_id ON favorite_posts(post_id) STORING (user_id);

-- favorite_replies (formerly favorite_comments)
CREATE TABLE IF NOT EXISTS favorite_replies (
favorite_reply_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
reply_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_favorites_replies_user_id ON favorite_replies(user_id) STORING (reply_id);
CREATE INDEX IF NOT EXISTS idx_favorites_replies_reply_id ON favorite_replies(reply_id) STORING (user_id);

-- flagged_posts (formerly flagged_topics)
CREATE TABLE IF NOT EXISTS flagged_posts (
flagged_post_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
post_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_flagged_posts_post_id ON flagged_posts(post_id);

-- flagged_replies (formerly flagged_comments)
CREATE TABLE IF NOT EXISTS flagged_replies (
flagged_reply_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
reply_id INT NOT NULL,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_flagged_replies_reply_id ON flagged_replies(reply_id);

-- post_poll_votes (formerly poll_votes)
CREATE TABLE IF NOT EXISTS post_poll_votes (
poll_vote_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
post_id INT NOT NULL,
user_id INT NOT NULL,
poll_choice INT NOT NULL CHECK (poll_choice BETWEEN 1 AND 4),
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_post_poll_votes_post_id_user_id ON post_poll_votes(post_id, user_id);

-- reply_notifications (formerly notifications, but only for reply-related notifications)
CREATE TABLE IF NOT EXISTS reply_notifications (
notification_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id INT NOT NULL,
reply_id INT,
read BOOL DEFAULT false,
seen BOOL DEFAULT false,
create_date TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reply_notifications_user_id_create_date_read_seen ON reply_notifications(user_id, create_date, read, seen);
CREATE INDEX IF NOT EXISTS idx_reply_notifications_reply_id ON reply_notifications(reply_id);

-- ================================
-- TAG DATA (unchanged from original)
-- ================================

INSERT INTO tags (tag_name, subtitle) VALUES
('politics', 'Uniting our divides'),
('media', 'Movies, TV, books'),
('religion', 'Ethics, philosophy'),
('animals', 'Pets, nature'),
('asks', 'Requests, questions'),
('polls', 'Multiple choice'),
('sports', 'Anything competitive'),
('history', 'Anything before 2010'),
('weather', 'Seasons, environment'),
('food', 'Cooking, farming'),
('parenting', 'Advice, experiences'),
('health', 'Physical and mental'),
('science', 'Testing the falsifiable'),
('work', 'Jobs and money')
ON CONFLICT (tag_name) DO NOTHING;


      `);
		} catch (err) {
			console.error("error executing query:", err)
		} finally {
			client.release()
		}
	},
}