const path = require("path")
const {
	setupIntegrationTestEnvironment,
} = require("./clientServerTestSetup.js")
const { assertEquals, runTests } = require("../client/shared/testUtils.js")

const tests = {
	testClientServerFlow: async () => {
		const window = await setupIntegrationTestEnvironment({
			beforeParse(window){
				window.localStorage.setItem("trucev1:session_uuid", "test-session-uuid-123")
				window.localStorage.setItem("trucev1:agreed", true)
				window.localStorage.setItem("trucev1:last_root_path", "/posts")
				
				// Set up external mocks before any scripts run
				window.setupExternalMocks()
				
				// Register async fetch handlers for early requests to prevent failures
				window.mockAsyncFetch("/session", '{"path":"/"}')
				window.mockAsyncFetch("/session", '{"path":"/unread_count_unseen_count"}')
				window.mockAsyncFetch("/session", '{"path":"/posts"}')
				window.mockAsyncFetch("/session", '{"path":"/topics"}')
				
			},
			databaseMocks: {
				sessionValidation: (sql, params) => {
					if (sql.includes("SELECT") && sql.includes("sessions.session_uuid") && sql.includes("users.display_name")) {
						if (params && params[0] === "test-session-uuid-123") {
							return { 
								rows: [{ 
									session_uuid: "test-session-uuid-123",
									session_id: 1, 
									email: "test@example.com",
									display_name: "Test User",
									admin: false,
									user_id: 1,
									profile_picture_uuid: null,
									slug: "test-user",
									subscribed_to_users: "0"
								}] 
							}
						}
					}
				},
				notifications: (sql, params) => {
					if (sql.includes("WITH combined_notifications") || sql.includes("unseen_count")) {
						return { 
							rows: [{ 
								unseen_count: 0,
								unread_count: 0
							}] 
						}
					}
				},
				posts: (sql, params) => {
					if (sql.includes("SELECT") && sql.includes("p.create_date") && sql.includes("p.post_id")) {
						return { 
							rows: [
								{
									post_id: 1,
									title: "My Post",
									body: "This is my own post",
									create_date: "2024-01-02T00:00:00.000Z",
									user_id: 1, // Same as our logged-in user
									reply_count: 0,
									favorite_count: 0,
									topics: "religion,media",
									edit: true
								},
								{
									post_id: 2,
									title: "Other User's Post", 
									body: "This is someone else's post",
									create_date: "2024-01-01T01:00:00.000Z",
									user_id: 2, // Different user
									reply_count: 0,
									favorite_count: 0,
									topics: "religion,media",
									edit: false
								}
							] 
						}
					}
				},
				topics: (sql, params) => {
					/*
						NOTE TO CLAUDE:
							I am leaving this large comment block here, as guidance to you for
							how to go about mocking new queries.
							
							(1) Find the query that you are working with in the server handler
							(2) Find the table schemas in schema.js for each table involved

						-- Table Schemas from schema.js
						CREATE TABLE IF NOT EXISTS post_topics (
						post_id INT NOT NULL,
						topic_id INT NOT NULL
						)
						CREATE TABLE IF NOT EXISTS topics (
						topic_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
						topic_name VARCHAR(10) NOT NULL UNIQUE,
						subtitle VARCHAR(50) NOT NULL
						)

						-- The query we are working with from getTopics.js
						SELECT
							ts.topic_name,
							ts.subtitle,
							COUNT(tt.topic_id) AS posts
						FROM
							topics ts
							LEFT JOIN post_topics tt ON ts.topic_id = tt.topic_id
						GROUP BY
							ts.topic_id,
							ts.topic_name,
							ts.subtitle
						ORDER BY ts.topic_id ASC
					*/
					if (sql.includes("SELECT") && sql.includes("topics ts") && sql.includes("COUNT(tt.topic_id) AS posts")) {
						return { 
							rows: [
								{ topic_name: "religion", subtitle: "Discussions about religion", posts: 2 },
								{ topic_name: "media", subtitle: "Media discussions", posts: 2 }
							] 
						}
					}
				}
			}
		})
		const { $ } = window
		
		$("main-content-2 posts post:first-child icon[more]").click()
		assertEquals(false, Boolean($("modal action[block]")), "Own post should not show block action")
		$("modal-bg").click()
		$("main-content-2 posts post:nth-child(2) icon[more]").click()
		assertEquals(true, Boolean($("modal action[block]")), "Other user's post should show block action")

		// Proof things (which have no fetch) happen instantly and no setTimeout is needed
		assertEquals(true, Boolean($("modal-bg")), "Modal is shown")
		$("modal-bg").click()
		assertEquals(false, Boolean($("modal-bg")), "Modal is closed")

		// Proof things which fetch require a setTimeout of ONLY JUST ZERO
		$(`footer [href="/topics"]`).click()
		assertEquals(
			0,
			$("main-content-wrapper topics topic")?.length || 0,
			"While loading, we do not have the topics yet",
		)
		assertEquals(
			true,
			Boolean($("posts-loading")),
			"While loading, we have a loading indicator",
		)
		await new Promise(resolve => setTimeout(resolve, 0))
		assertEquals(
			2,
			$("main-content-wrapper topics topic")?.length || 0,
			"After loading, we have 2 topics",
		)
		assertEquals(
			false,
			Boolean($("posts-loading")),
			"After loading, we do not have a loading indicator",
		)

		/*
			NOTE TO CLAUDE:

			How do you write code that checks innerText?
				(1) Find the DOM structure you are interested in in the code
				(2) Use a console.warn to out the innerHTML of something close
				(3) Find the actual element to get innerText from
				(4) DELETE the console.warn of innerHTML - This was for your discovery purposes ONLY

			// Dom Structure for topics from renderTopics.js:
				topic[topic=$1]
					icon
						$2
					topicname-subtitle
						topicname
							name $3
							count $4
						subtitle $5
			
			// This:
			console.warn($("main-content-wrapper topics topic:nth-child(1) topicname-subtitle").innerHTML)
			// Would output:
			// <topicname><name></name><count></count></topicname><subtitle></subtitle>

			// Which tells us, that the selector we need to find innerText is:
			$("main-content-wrapper topics topic:nth-child(1) topicname-subtitle topicname name").innerText

			// We cannot use:
			$("main-content-wrapper topics topic:nth-child(1) topicname-subtitle topicname").innerText
			// Because jsdom does not propagate innerText to the parent element

		*/
		assertEquals(
			"Religion",
			$("main-content-wrapper topics topic:nth-child(1) topicname-subtitle topicname name").innerText,
			`First topic name should be "Religion"`,
		)
		assertEquals(
			"2",
			$("main-content-wrapper topics topic:nth-child(1) topicname-subtitle topicname count").innerText,
			`First topic post count should be "2"`,
		)
	},
}

runTests(path.basename(__filename), Object.values(tests))